language: scala
before_script:
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - sudo DEBIAN_FRONTEND=noninteractive apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install dsc30
#  - sudo service cassandra start
  - java -version
script:
  - sbt -J-Xmx4G clean test doc
scala:
  - 2.12.0
jdk:
  - oraclejdk8

sudo: required
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
