language: scala

before_script:
  - which cassandra
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz && tar -xvzf apache-cassandra-3.9-bin.tar.gz
  - sudo sh ./apache-cassandra-3.9/bin/cassandra -R -E cassandra-error.txt
  - tail -f cassandra-error.txt &
  - sleep 20

script:
  - sbt -J-Xmx4G clean test doc

scala:
  - 2.12.0

jdk:
  - oraclejdk8

sudo: required
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
